stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py Training
    deps:
      - .\src\data\make_dataset.py
      - .\data\raw\Training
    params:
      - make_dataset.image_size
      - make_dataset.test_size
      - make_dataset.random_state
    outs:
      - .\data\interium

  data_preprocessing:
    cmd: python .\src\features\data_preprocessing.py X_train y_train X_val y_val
    deps:
      - .\src\features\data_preprocessing.py
      - .\data\interium
    outs:
      - .\data\processed

  train_model:
    cmd: python .\src\models\train_model.py .\data\processed
    deps:
      - .\src\models\train_model.py
      - .\data\processed
    params:                                                                                                                                                                                                 
      - make_dataset.image_size
      - train_model.epochs
      - train_model.batch_size
      - train_model.model_name
    outs:
      - .\models

  predict_model:
    cmd: python .\src\models\predict_model.py .\data\raw\Testing
    deps:
      - .\src\models\predict_model.py
      - .\models
      - .\data\raw\Testing
    outs:
      - .\reports
